export const FETCH_ROOMS = 'FETCH_ROOMS';
export const UPDATE_ROOMS_FETCHING_STATUS = 'UPDATE_ROOMS_FETCHING_STATUS';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_ROOM = 'SELECT_ROOM';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';
